name: Little Blinking Lights
description: Blog of Tyler Hoeflicker
avatar: ../images/avatar.jpeg
footer-links:
  dribbble: 
  email: 
  facebook: 
  flickr: 
  github: tylerflick
  instagram: 
  linkedin: 
  pinterest: 
  rss: # just type anything here for a working RSS icon, make sure you set the "url" above!
  twitter:
  stackoverflow: users/1821331/tylerflick
disqus: 
google_analytics:

url: blog.tylerflick.com
markdown: redcarpet
highlighter: pygments

permalink: pretty

version: v1.0.0

sass:
  sass_dir: _assets/_stylesheets/
  style: :compressed

gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem

exclude: ["bower.json", ".sass-cache", ".gitignore"]
